# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1_Layout_and_Stacks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 1_Layout_and_Stacks
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore' 

end
